### ISSUE TITLE
My Own image inference

### ISSUE THREAD

**Issue by puppy9207** [ZhanxyR/SHERT#3]
![partial_tex](https://github.com/user-attachments/assets/59774683-48c1-4ec2-b3a5-1feef0f90913)

<img width="527" alt="image" src="https://github.com/user-attachments/assets/beec61a3-6b7a-4ace-8659-efcaf7a3a58b">

I took my image and made it based on the data from ECON + EMOCA. As you said in the [previous issue](https://github.com/ZhanxyR/SHERT/issues/2), EMOCA can solve face alignment, but even if I put the results from EMOCA, my face comes out weird. Is there anything I missed? Below is config.yaml.

```
# Do not forget to modify the root dir
root: "./examples/demo_image"

# Set to False to skip
settings:
  use_econ: False
  # subdivide: False
  # sns: False
  # complete: False
  use_emoca_face: True
  face_smooth: False
  # refine: False
  # color_projection: False

files:
  image: "front_origin.png"
  mask: "front_mask.png"
  front_normal: "front_normal_f.png"
  back_normal: "front_normal_b.png"
  mesh: "front_0_full.obj"
  smplx_param: "front_smpl_00.npy"
  smplx: "front_smpl_00.obj"
  emoca_face: "mesh_coarse_detail.obj"

parameters:
  # <-- Change as desired -->
  sns:
    use_thuman_smplx_param: False
    # smplx_gender: 'neutral'
    # t_max_sample_dis: 0.1
    # t_angle: 2
    # t_area: 3
    # t_edge: 3
    # t_s_angle: 2
    # t_s_area: 3
    # t_s_edge: 3
    # t_s_connect: 500
  inpaint:
    # TODO: dilation:
    use_smplx: None #[None, 'face', 'head']
  refine:
    normal_flip: False
    # refine_iter: 2  # need pytorch3d if greater than 1
    # smooth_iter: 3
    # smooth_lambda: 0.5
  color_projection:
    front_only: True
  #   vertex_color: False


```
